@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "ivan",
  "password": "12345678",
  "email": "ptrofimov7@gmail.com",
  "avatarColor": "red",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKcAAADlCAIAAAC55HDcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAICSURBVHhe7dEBDQAwCMCwu0Em0rmQNamDvtuhxnqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1ousF1kvsl5kvch6kfUi60XWi6wXWS+yXmS9yHqR9SLrRdaLrBdZL7JeZL3IepH1IutF1nt2PlHsuiudwpqLAAAAAElFTkSuQmCC"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "ivan",
  "password": "12345678"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": ""
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/<token>
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "",
  "confirmPassword": ""
}
